
services:
  postgres:
    image: postgres:15
    container_name: hotel_postgres
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hotel_db
    volumes:
      - hotel_pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: hotel_app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres
    expose:
      - "8080"

  caddy:
    image: caddy:2-alpine
    container_name: hotel_caddy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app

volumes:
  hotel_pgdata:
