
services:
  postgres:
    image: postgres:15
    container_name: hotel_postgres
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hotel_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
