
services:
  postgres:
    image: postgres:15
    container_name: hospitality_postgres
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hospitality_db
    volumes:
      - hospitality_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: hospitality_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - hospitality_redis_data:/data

  app:
    build: .
    container_name: hospitality_app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres
      - redis
    expose:
      - "8080"

  caddy:
    image: caddy:2-alpine
    container_name: hospitality_caddy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app

volumes:
  hospitality_pgdata:
  hospitality_redis_data:
